In [1]:
"""
    import shuffle

    notes:  
    
    https://pynative.com/python-random-shuffle/

    allows to:      
           - Shuffle a list and string
           - Shuffle two Python List at once with the same order
           - Shuffling multidimensional array in Python
           
    IMPORTANT
           - shuffles IN PLACE !!!
           -  see below hot to avoid it !
    
"""


# --------------------------------
# Shuffle a list and string

import random
number_list = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
print ("Original list : ",  number_list)

random.shuffle(number_list) #shuffle method
print ("List after first shuffle  : ",  number_list)

random.shuffle(number_list)
print ("List after second shuffle : ",  number_list)
print("\n","\n")


# --------------------------------
#Shuffle list to get the same result every time


numbers = [10, 20, 30, 40, 50, 60]
print ("Original list: ", numbers )
random.seed(4)
random.shuffle(numbers)
print("reshuffled list ", numbers)

numbers = [10, 20, 30, 40, 50, 60]
random.seed(4)
random.shuffle(numbers)
print("reshuffled list ", numbers)
print("\n","\n")


# --------------------------------
# Shuffle NOT IN PLACE
#.       we need to use a random.sample() function

numbers = [5, 10, 15, 20, 25]
print ("Original list : ",  numbers)

new_list = random.sample(numbers, len(numbers))
print ("List after not in-place shuffle  : ",  new_list)
print("\n","\n")


# --------------------------------
# Shuffle two Python List at once with the same order
#.       use list( zip( list1, list2 ) )

# example: employees data:
empName = ['Jhon', 'Emma', 'Kelly', 'Jason']
empSalary = [7000, 6500, 9000, 10000]

print("Print Lists Before Shuffling")
print("List Employee Names: ", empName)
print("List Employee Salary: ", empSalary)

mapIndexPosition = list(zip(empName, empSalary)) # turns list1 and 2 into one list with tuplkes, wiht (el1_list1, el1, list2) ...
                                                 # [('Jhon', 7000), ('Emma', 6500), ('Kelly', 9000), ('Jason', 10000)]
# now shuffle that new list
random.shuffle(mapIndexPosition) # shuffle inplace :)

# unzip
empName, empSalary = zip(*mapIndexPosition)

print("\nPrint Lists after Shuffling")
print("List Employee Names: ", empName)
print("List Employee Salary: ", empSalary,"\n","\n")



# --------------------------------
# Shuffling multidimensional array in Python
#.       CAUTION : it mixes position of all cells, in arr.flatten()

import numpy

print("Before Shufflling 2-dimensional array in Python")
sampleArray = numpy.arange(100, 240, 10)
sampleArray = sampleArray.reshape(2,7)
print (sampleArray,"\n")

print("After Shufflling 2-dimensional array in Python")
newArray = numpy.random.shuffle(sampleArray)
print (sampleArray)

Original list :  [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
List after first shuffle  :  [49, 63, 56, 14, 35, 21, 28, 70, 42, 7]
List after second shuffle :  [35, 42, 28, 14, 63, 21, 49, 56, 70, 7]

 

Original list:  [10, 20, 30, 40, 50, 60]
reshuffled list  [40, 60, 50, 10, 30, 20]
reshuffled list  [40, 60, 50, 10, 30, 20]

 

Original list :  [5, 10, 15, 20, 25]
List after not in-place shuffle  :  [20, 10, 5, 15, 25]

 

Print Lists Before Shuffling
List Employee Names:  ['Jhon', 'Emma', 'Kelly', 'Jason']
List Employee Salary:  [7000, 6500, 9000, 10000]

Print Lists after Shuffling
List Employee Names:  ('Jhon', 'Emma', 'Kelly', 'Jason')
List Employee Salary:  (7000, 6500, 9000, 10000) 
 

Before Shufflling 2-dimensional array in Python
[[100 110 120 130 140 150 160]
 [170 180 190 200 210 220 230]] 

After Shufflling 2-dimensional array in Python
[[170 180 190 200 210 220 230]
 [100 110 120 130 140 150 160]]
